(* Generated by Lem from lem/word256.lem. *)

Require Import Arith.
Require Import Bool.
Require Import List.
Require Import String.
Require Import Program.Wf.

Open Scope nat_scope.
Open Scope string_scope.


Lemmabs_to_w256_def_lemma:((forallseq,(classical_boolean_equivalence match ( resizeBitSeq (Some( 256%nat)) seq) with 
 | BitSeq _ s b => W256 s b
end ((fun (w : bitSequence ) => Z_to_two_compl 255 (integerFromBitSeq w)) seq) : Prop)): Prop) .
Lemmaw256_to_bs_def_lemma:((foralls b,(classical_boolean_equivalence (BitSeq (Some( 256%nat)) s b) 
  ((fun (w : (Bvector  256) ) =>
      bitSeqFromInteger (Some 256%nat) ((two_compl_value 255 w))) (W256 s b)) : Prop)): Prop) .
Lemmaword256ToInteger_def_lemma:((forallw,(Z.eqb (integerFromBitSeq ((fun (w : (Bvector  256) ) => bitSeqFromInteger (Some 256%nat) ((two_compl_value 255 w))) w)) 
  ((two_compl_value 255 w)) : Prop)): Prop) .

